name: AIBA Components UAT

on:
  push:
    branches:
      - development
    paths:
      - "packages/ui-components/src/**"

jobs:
  job_deploy_components:
    name: "Deploy AIBA Components"
    environment: UAT
    env:
      GIT_CLONE_USER_MAIL: ${{vars.GIT_CLONE_USER_MAIL}}
      GIT_CLONE_USER_NAME: ${{vars.GIT_CLONE_USER_NAME}}
      GIT_CLONE_CREDENTIALS: ${{secrets.GIT_CLONE_CREDENTIALS}}
    runs-on: "ubuntu-latest"
    steps:
      - id: "code_checkout"
        uses: actions/checkout@v3

      - name: "authorization"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{secrets.STAGE_GCP_CREDENTIALS}}"

      - name: "set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: AIBA Components Package Build and Deploy
        run: |
          yarn install && yarn build
          git clone https://${{ env.GIT_CLONE_CREDENTIALS }}@bitbucket.org/avinash_digital20_platform/aiba-component-library.git
          cd aiba-component-library
          git checkout release_components_uat@v2.1.1
          cd ..
          ls
          cp packages/ui-components/dist/* aiba-component-library -rf
          cd aiba-component-library
          git branch -a
          ls
          git config --global user.email ${{ env.GIT_CLONE_USER_MAIL }}
          git config --global user.name ${{ env.GIT_CLONE_USER_NAME }}
          git add .
          git commit -m "Updated UI Components Library"

          # Generate release notes
          latest_tag=$(git describe --tags --abbrev=0)
          commit_messages=$(git log --oneline $latest_tag..HEAD)
          echo "Release Notes" > release_notes.txt
          echo "=========================" >> release_notes.txt
          echo "Latest Tag: $latest_tag" >> release_notes.txt
          echo "" >> release_notes.txt
          echo "Changes:" >> release_notes.txt
          echo "$commit_messages" >> release_notes.txt

          # Create GitHub release
          tag_name=$(git rev-parse --short HEAD)
          release_name="Release $tag_name"
          echo "Creating GitHub release: $release_name"
          echo "::set-output name=tag_name::$tag_name"
          echo "::set-output name=release_name::$release_name"
          echo "::set-output name=release_notes::$(cat release_notes.txt)"

          # Push changes and tag to GitHub
          git push origin release_components_uat@v2.1.1
          git tag $tag_name
          git push origin $tag_name

          ls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{vars.SONAR_HOST_URL}}

      - name: AIBA StoryBook Build & Deploy
        env:
          GCS_BUCKET_NAME: ${{vars.GCS_BUCKET_NAME}}
          GCS_REMOTE_PATH: ${{vars.GCS_REMOTE_PATH}}
        run: |
          mkdir -p storybookbuild/${{env.GCS_REMOTE_PATH}}/
          echo ${{env.GCS_REMOTE_PATH}}
          yarn install
          yarn build
          yarn build-storybook
          cp -rv ./packages/ui-components/storybook-static/* ./storybookbuild/${{env.GCS_REMOTE_PATH}}
          ls -ltr
          ls -ltr storybookbuild
          gsutil -m rsync -r -d ./storybookbuild/${{env.GCS_REMOTE_PATH}} gs://${{env.GCS_BUCKET_NAME}}/${{env.GCS_REMOTE_PATH}}
          echo "URL = https://aiba-uat.unileversolutions.com/${{env.GCS_REMOTE_PATH}}/index.html"

      - name: AIBA Unit Test Coverage Report Generation
        env:
          GCS_UNIT_TEST_REPORT_PATH: ${{vars.GCS_UNIT_TEST_REPORT_PATH}}
          GCS_BUCKET_NAME: ${{vars.GCS_BUCKET_NAME}}
        run: |
          mkdir -p coveragereport/${{env.GCS_UNIT_TEST_REPORT_PATH}}/
          echo ${{env.GCS_UNIT_TEST_REPORT_PATH}}
          apt-get update
          apt-get install libnss3-dev libatk-bridge2.0-0 libdrm2 libgbm1 libxkbcommon0 libasound2 libcups2 libxcomposite1 libxdamage1 libxrandr2 libxfixes3 -y
          yarn install
          yarn test --silent --coverage -u
          ls
          cp -rv ./packages/ui-components/coverage/* ./coveragereport/${{env.GCS_UNIT_TEST_REPORT_PATH}}
          ls -ltr
          ls -ltr coveragereport
          export GCS_UNIT_TEST_REPORT_PATH=${{env.GCS_UNIT_TEST_REPORT_PATH}}
          gsutil -m rsync -r -d ./coveragereport/${{env.GCS_UNIT_TEST_REPORT_PATH}} gs://${{env.GCS_BUCKET_NAME}}/${{env.GCS_UNIT_TEST_REPORT_PATH}}
          echo "URL = https://aiba-uat.unileversolutions.com/${{env.GCS_UNIT_TEST_REPORT_PATH}}/lcov-report/index.html"
