name: Print Secrets and Environment UAT

on: 
  push:
    branches:
      - main

jobs:
  job_print_secrets:
    name: "Print Secrets and Environment"
    environment: ${{vars.ENV_STAGE}}
    runs-on: 'ubuntu-latest'
    steps:
      - id: 'code_checkout'
        uses: actions/checkout@v3
      
      - name: Access Repository-level Secret
        run: |
             echo "Repository-level secret:${{ secrets.COMMON_REPO_SECRET }}" | sed 's/./& /g'
             echo "Organization-level secret:${{ secrets.COMMON_ORG_SECRET }}" | sed 's/./& /g'
             echo "Repository-level environment variable:${{ vars.COMMON_REPO_VARIABLE }}"
             echo "Organization-level environment variable:${{ vars.COMMON_ORG_VARIABLE }}"
             echo "Organization-level environment variable:${{ vars.ENV_REPO_VARIABLE }}"
             echo "Organization-level environment variable:${{ secrets.ENV_REPO_SECRET }}" | sed 's/./& /g'
             echo "Organization-level environment variable:${{ secrets.${{vars.ENV_STAGE}}_GCP_CRED }}" | sed 's/./& /g'
             echo "Organization-level environment variable:${{ vars.${{vars.ENV_STAGE}}_GCP_CRED_VAR }}"
             echo "Github environment: ${{vars.ENV_STAGE}}"


