name: AIBA Services UAT

on:
  push:
    branches:
      - development
    # paths:
    #   - "packages/ui-services/src/**"

jobs:
  job_deploy_services:
    name: "Deploy AIBA Services"
    environment: UAT
    env:
      GIT_CLONE_USER_MAIL: ${{vars.GIT_CLONE_USER_MAIL}}
      GIT_CLONE_USER_NAME: ${{vars.GIT_CLONE_USER_NAME}}
      GIT_CLONE_CREDENTIALS: ${{secrets.GIT_CLONE_CREDENTIALS}}
    runs-on: "ubuntu-latest"
    steps:
      - id: "code_checkout"
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email ${{env.GIT_CLONE_USER_MAIL}}
          git config --global user.name ${{env.GIT_CLONE_USER_NAME}}

      - name: Clone Repository
        run: |
          git clone https://github.com/Aayushman-Chatterjee-Organization/aayushman-test-repo-v2.git temp_repo
          # git clone https://${{ env.GIT_CLONE_CREDENTIALS }}@github.com/UL-AIBA/aiba-component-library.git temp_repo
          cd temp_repo

      - name: AIBA UI Services Package Build and Deploy
        env:
          GITHUB_TOKEN: ${{secrets.GIT_CLONE_CREDENTIALS}}
        run: |
          # yarn install
          # yarn build-ui-services
          # git clone https://${{ env.GIT_CLONE_CREDENTIALS }}@bitbucket.org/avinash_digital20_platform/aiba-component-library.git
          # git clone https://${{ env.GIT_CLONE_CREDENTIALS }}@github.com/UL-AIBA/aiba-component-library.git
          # git clone https://github.com/Aayushman-Chatterjee-Organization/aayushman-test-repo-v2.git
          # cd aiba-component-library 
          # cd aayushman-test-repo-v2
          # cd .. 

          ls
          # cp packages/ui-services/dist/* aiba-component-library -rf
          # cd aiba-component-library

          git branch -a
          ls

          # if git rev-parse --verify --quiet release_services_uat@v2.1.9 > /dev/null; then
          if git show-ref --verify --quiet refs/heads/release_services_uat@v2.1.9; then
            echo "[release_services_uat@v2.1.9] Branch exists"
            git checkout release_services_uat@v2.1.9 
            git pull origin release_services_uat@v2.1.9
            git add . 
            git commit -m "Updated UI Services Library"
            git push origin release_services_uat@v2.1.9
            commit_id=$(git rev-parse HEAD)
            git tag -a v2.1.9 $commit_id -m "v2.1.9 tag added"
            git push origin v2.1.9
          else
            echo "[release_services_uat@v2.1.9] Branch created"
            git checkout -b release_services_uat@v2.1.9
            git add .
            git commit -m "Updated UI Services Library" 
            git push origin release_services_uat@v2.1.9
            commit_id=$(git rev-parse HEAD) 
            git tag -a v2.1.9 $commit_id -m "v2.1.9 tag added"
            git push origin v2.1.9 
          fi 
          ls

      # - name: SonarQube Scan
      #   uses: sonarsource/sonarqube-scan-action@master
      #   env:
      #     SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      #     SONAR_HOST_URL: ${{vars.SONAR_HOST_URL}}
